apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ppt
  labels:
    app: sk
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sk
  template:
    metadata:
      labels:
        app: sk
    spec:
      containers:
      - name: sk1
        image: nginx:latest
        ports:
        - containerPort: 80
